### ISSUE TITLE
Benchmark was performed with hasPhoneNumber?

### ISSUE THREAD

**Issue by Bramzor** [dbaq/cordova-plugin-contacts-phone-numbers#54]
I was wondering if you performed the benchmark with hasPhoneNumber on true in the official plugin? Or was this option not available at that time?

Wondering if I still need to combine both the plugins or if it was fixed with hasPhoneNumber in the official plugin.

**Comment by dbaq** [comment]
hey @Bramzor,

That option was not available at that time (4 years ago).  I truly hope they improved the performance since then. I am just keeping this plugin up to date because developers are still using it. 
If you want to run a performance test, make sure to use a phone with a google account linked with a lot of google contacts on top of the phone contacts.
